# Change these first
owner: cannavit # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  # Prenotazioni
  - name: Anoki prenotazioni-api [production]
    url: https://prenotazioni-api.cloud.anoki.it/reservation-be/swagger-ui.html
  - name: Anoki prenotazioni-web [production]   
    url: https://prenota.cloud.anoki.it/
    
  # Edutelling
  - name: Edutelling Web Product [production]
    url: https://edutelling.it/
    logoUrl: https://edutelling.it/media/logo.svg
    
  - name: Edutelling WEB itkif [Production]
    url: https://itkif.edutelling.it/login
    logoUrl: https://edutelling.it/media/logo.svg
    
  - name: Edutelling WEB jac [Production]
    url: https://jac.edutelling.it/login
    logoUrl: https://edutelling.it/media/logo.svg
    
  - name: Edutelling API pacinottibelmesseri [Production]
    url: https://pacinottibelmesseri-be.edutelling.it/api/v1/auth/authentication
    method: POST
    body: '{ "email": "formazione@edutelling.it", "password": "Passw0rd", "stayLogged": false }'
    headers:
      - "Content-Type: application/json"
    expectedStatusCodes:
      - 404
    
  - name: Edutelling WEB pacinottibelmesseri [Production] 
    url: https://pacinottibelmesseri.edutelling.it/login
    logoUrl: https://edutelling.it/media/logo.svg
    
  # Fantaking Staging  (DISABLED)
  # - name: Fantaking backend [STAGING]
  # url: http://dev3-fantaking.dunkest.com/telescope/requests
  
  # POT PROJECT
  - name: POT WEB [Staging]
    url: https://pot-uat.paxitalia.com:5443
  - name: POT API [Staging]
    url: http://pot-uat.paxitalia.com:8443/api/public/auth/signin
    method: POST
    body: '{ "password": "test", "usernameOrEmail": "test@test.com" }'
    headers:
      - "Content-Type: application/json"
    expectedStatusCodes:
      - 401
      - 403
      - 400
      
  - name: POT WEB [Production]
    url: https://pot.paxitalia.com/
  - name: POT API [Production]
    url: https://pot.paxitalia.com:8443/api/public/auth/signin
    method: POST
    body: '{ "password": "test", "usernameOrEmail": "test@test.com" }'
    headers:
      - "Content-Type: application/json"
    expectedStatusCodes:
      - 401    
      - 403
      - 400
      
assignees:
  - cannavit

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#   cname: demo.upptime.js.org
  cname: cannavit.github.io/upptime
  # baseUrl: /your-repo-name
  baseUrl: upptime
#   logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://anoki.it/img/anokilogo.ba6c1ee9.png
  name: Anoki Status Pages
  introTitle: "**Anoki** Projects Status Page"
#   introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  introMessage: This page monitors the status of Anoki's pages and services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
