# Change these first
owner: cannavit # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Anoki Rancher Production Cluster
    url: https://cloud.anoki.it:8443/dashboard/auth/login
  - name: Anoki Rancher Developer Cluster
    url: https://openshift.techgap.it:8443/login
  - name: Anoki prenotazioni-api [production]
    url: http://prenotazioni-api.cloud.anoki.it/reservation-be/swagger-ui.html
  - name: Anoki prenotazioni-web [production]   
    url: http://prenotazioni-web.cloud.anoki.it/

assignees:
  - cannavit

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: upptime
#   logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://anoki.it/img/anokilogo.ba6c1ee9.png
  name: Anoki Status Pages
  introTitle: "**Anoki** Projects Status Page"
#   introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  introMessage: This page monitors the status of Anoki's pages and services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
